### ISSUE TITLE
addComponent with initial value

### ISSUE THREAD

**Issue by zewa666** [NateTheGreatt/bitECS#105]
I'd like to know if its planned to have some sort of convenience helpers for addComponent. often I do want to add a component and straight away initialize it with a default value for all of the components props.

In the meantime I came up with the following which wraps the original addComponent from BitECS:

```ts
export function addComponent<T extends ISchema>(
  world: IWorld,
  component: ComponentType<T>,
  eid: number,
  initValue?: {
    [key in keyof T]: T[key] extends [string, number] ? number[] : number;
  },
  reset?: boolean | undefined
): void {
  bitecsAddComponent(world, component, eid, reset);
  if (!initValue) {
    return;
  }

  Object.entries(initValue as Record<string, number | number[]>).forEach(
    ([key, value]) => {
      if (Array.isArray(value)) {
        (
          (component as ComponentType<{ [key: string]: ISchema }>)[key][
            eid
          ] as TypedArray
        ).set(value);
      }
      (component as ComponentType<{ [key: string]: ISchema }>)[key][eid] =
        value;
    }
  );
}


// For a component like this:
export const Attacked = defineComponent({
  enemy: Types.eid,
  originX: Types.i8,
  originY: Types.i8,
  ranged: Types.i8
});
```

![2023-01-17_20-12](https://user-images.githubusercontent.com/2861414/212990555-4edf0da6-ace2-4fa6-bf8f-456f9a72570f.png)

**Comment by NateTheGreatt** [comment]
i try to make bitECS as performant as possible, and let the users degrade the performance where appropriate for their particular use-case. one of the keys to this is creating as little garbage as possible so that the GC has nothing to clean up, and that is accomplished by pre-allocating everything up-front. technically this new function of yours, while syntactically cleaner, creates an object every time you add a component. the original `addComponent` creates no objects and therefor has no chance creating any garbage to clean up.

my goal with bitECS is to do less for the user and remain as flexible as possible for all potential use-cases. this function does more for the user, and creates objects, so i won't be adding anything like this into the API.

not to say i discourage functions like this, just want to keep GC-generating things outside of the API. all depends on your use-case :)

**Comment by zewa666** [comment]
thanks for the detailed explanation and pretty much what I anticipated.
