### ISSUE TITLE
hello, fellow ECS project!

### ISSUE THREAD

**Issue by mreinstein** [NateTheGreatt/bitECS#24]
Hey there, cool looking project! It's really great to see people promoting data-oriented game architecture, there aren't many of us.

I've got a very similar project over at https://github.com/mreinstein/ecs

I don't know if there's significant ways that we can help each other out, but maybe there are resources/ideas we could share to make both of these ECS projects better:

* I'd love to see how mine performs on the bitECS benchmarks. I haven't done any formalized benchmark testing, but when running it in my game prototypes the time spent is way under 1% of total CPU time.
* I have a functional (but crappy looking) chrome extension that is able to read ECS world data from the page and display it in a devtools panel. Maybe this is something we could make common, or you could copy/paste into bitECS

I also added a link to bitECS at the bottom of my README, in the interests of spreading interest in data-oriented tools. :)

Anyway just wanted to say great job, and good to see these implementations _not_ based on Object Oriented Blech-gramming.

**Comment by NateTheGreatt** [comment]
thanks for the shoutout and reaching out! indeed there is a severe lack of data-oriented game archs out there.

> I'd love to see how mine performs on the bitECS benchmarks. I haven't done any formalized benchmark testing, but when running it in my game prototypes the time spent is way under 1% of total CPU time.

if i were to guess i'd say it will perform equivalently to [uecs](https://github.com/jprochazk/uecs) at best, due to the component stores being object-based. if you use entity IDs as pointers into TypedArrays like bitECS and [wolf-ecs](https://github.com/EnderShadow8/wolf-ecs) do, you will see close to an entire order of magnitude boost in iteration speed.

> I have a functional (but crappy looking) chrome extension that is able to read ECS world data from the page and display it in a devtools panel. Maybe this is something we could make common, or you could copy/paste into bitECS

`bitECS` was created to be used inside of a web-based game engine that a friend and I have been working on for the last couple of years. since then it has has found its way into a few other larger projects like [Phaser 4](https://github.com/phaserjs/phaser) and soon [XREngine](https://github.com/XRFoundation/XREngine).

also 

> Object Oriented Blech-gramming

preach

**Comment by NateTheGreatt** [comment]
thanks for the shoutout and reaching out!

> I don't know if there's significant ways that we can help each other out, but maybe there are resources/ideas we could share to make both of these ECS projects better

there's a pretty active [discord community](https://discord.gg/qskTAan7) for several web-based ECS libs where we do a lot of sharing of the sort if you're interested, stop in and say hi! 

`bitECS` was originally created to build web-based multiplayer game engine that a friend and i have been working on since its inception, so it is a bit biased towards that use-case. was also recently adopted by a few larger FOSS projects like [Phaser 4](https://github.com/phaserjs/phaser) and soon [XREngine](https://github.com/XRFoundation/XREngine).

> I'd love to see how mine performs on the bitECS benchmarks. I haven't done any formalized benchmark testing, but when running it in my game prototypes the time spent is way under 1% of total CPU time.

if i were to guess i'd say its performance will be similar to [uecs](https://github.com/jprochazk/uecs) or [javelin-ecs](https://github.com/3mcd/javelin/tree/master/packages/ecs) at best, due to the component stores being object-based. if you do SoA and have entity IDs as pointers into TypedArrays like `bitECS` and [wolf-ecs](https://github.com/EnderShadow8/wolf-ecs) do, you can see up to an entire order of magnitude boost in iteration performance.

> I have a functional (but crappy looking) chrome extension that is able to read ECS world data from the page and display it in a devtools panel. Maybe this is something we could make common, or you could copy/paste into bitECS

we built a very similar chrome extension to [ESCY's devtools](https://github.com/ecsyjs/ecsy-devtools), but currently fairly integrated and closed source along with the engine at the moment. however, i would love to see a generic version of this which could be adapted to different ECS libs somehow. one interface to the UI, used by adapters written for any ECS lib. perhaps we can work towards this?

> Anyway just wanted to say great job

cheers, thank you and likewise!

> Object Oriented Blech-gramming

🥂
