### ISSUE TITLE
Queries defined outside of a system function only return new entity matches

### ISSUE THREAD

**Issue by luetkemj** [NateTheGreatt/bitECS#48]
Queries defined outside a system function will return all matches on the first call and only new matches on subsequent calls.

Queries defined inside a system function will always return all matches.

Created a minimal repro here: https://github.com/luetkemj/bitecs-bug-repro

I would expect that a query defined outside a system function would always return all matches. I would not expect to have to redefine it  every time the system runs to get this behavior.

**Comment by NateTheGreatt** [comment]
i think what might be confusing you is the fact that bitECS recycles entity IDs. there shouldn't be any issues if you allow bitECS to handle all EID management:
```js
import {
  addComponent,
  addEntity,
  createWorld,
  defineComponent,
  defineQuery,
  removeComponent,
} from "bitecs";

const world = createWorld();
const InFov = defineComponent();

// create 100 entities
for (let i = 0; i < 100; i++) {
  const eid = addEntity(world)
  // only add component to 25 entities
  if (i < 25) addComponent(world, InFov, eid);
}

// if the inFovQuery is defined outside of the fovSystem
// it only returns new entities that match the query
const inFovQuery = defineQuery([InFov]);

export const fovSystem = (world) => {
  // if it is defined inside of the query it returns all entities that match the query
  // const inFovQuery = defineQuery([InFov]);

  const inFovEnts = inFovQuery(world);

  console.log(`expect: 25, actual: ${inFovEnts.length}`);

  for (let i = 0; i < inFovEnts.length; i++) {
    const eid = inFovEnts[i];
    removeComponent(world, InFov, eid);
  }

  return world;
};

fovSystem(world);

// add fov component to 25 more entities
for (let i = 0; i < 25; i++) {
  const eid = addEntity(world)
  addComponent(world, InFov, eid);
}

fovSystem(world);
```

```
expect: 25, actual: 25
expect: 25, actual: 25
```

**Comment by vegeta897** [comment]
> i think what might be confusing you is the fact that bitECS recycles entity IDs.

This is not the problem; their test is not adding any new entities after the initial set.
Here is a simplified version of their test with only 3 entities:

1. Create entities A B and C
2. Add component to A and B
3. Run system, query contains A and B and the system removes component from them
4. Add component to B and C
5. Run system, query contains only entity C, expected B and C

```js
const world = createWorld();
const InFov = defineComponent();

// create entities A B and C
const entA = addEntity(world)
const entB = addEntity(world)
const entC = addEntity(world)

// add fov component to A and B
addComponent(world, InFov, entA);
addComponent(world, InFov, entB);

// if the inFovQuery is defined outside of the fovSystem
// it only returns new entities that match the query
const inFovQuery = defineQuery([InFov]);

export const fovSystem = (world) => {
  // if it is defined inside of the query it returns all entities that match the query
  // const inFovQuery = defineQuery([InFov]);

  const inFovEnts = inFovQuery(world);

  console.log(`expect: 2, actual: ${inFovEnts.length}`);

  for (let i = 0; i < inFovEnts.length; i++) {
    const eid = inFovEnts[i];
    removeComponent(world, InFov, eid);
  }

  return world;
};

fovSystem(world);

// add fov component to B and C
addComponent(world, InFov, entB);
addComponent(world, InFov, entC);

fovSystem(world);
```

```
expect: 2, actual: 2
expect: 2, actual: 1
```

**Comment by NateTheGreatt** [comment]
these components are being added to EIDs which have been removed:
 ```js
// add fov component to B and C
addComponent(world, InFov, entB);  // this entity was just removed from fovSystem()
addComponent(world, InFov, entC); // this entity was just removed from fovSystem()
 ```
 
 removed entities shouldn't appear in queries 😄

**Comment by vegeta897** [comment]
The system is removing components, not entities. Only your example is removing entities 😅

**Comment by NateTheGreatt** [comment]
oh right! i just noticed that. let me ponder this for a bit longer...

**Comment by luetkemj** [comment]
Thanks @vegeta897 for helping explain the issue!

**Comment by NateTheGreatt** [comment]
okay, bug identified! i'm not too sure if i can fix this without adding back `defineSystem`, which i attempted to deprecate recently.

basically, because removals are deferred (to avoid removals borking loops), `defineSystem` used to call `commitRemovals`. queries call this function, too. those two aformentioned `addComponent` calls were indeed adding the component, but deferred removals were removing the component from both entities the next time the query was called! 😆 

i will soon publish a fix for this. super simple! add `commitRemovals` to addComponent calls 😀

thanks much for creating the issue and persisting through my short-sightedness! 😵

**Comment by NateTheGreatt** [comment]
okay, bug identified!

basically, because removals are deferred (to avoid removals borking loops), defineSystem used to call commitRemovals. queries call this function, too. those two aformentioned addComponent calls were indeed adding the component, but deferred removals were removing the component from both entities the next time the query was called! 😆

i will soon publish a fix for this. super simple! add commitRemovals to addComponent calls 😀

thanks much for creating the issue and persisting through my short-sightedness! 😵

**Comment by NateTheGreatt** [comment]
okay, bug identified! not sure if i can fix this without adding back `defineSystem` but i shall ponder this for a bit.

basically, because removals are deferred (to avoid removals borking loops), defineSystem used to call commitRemovals. queries call this function, too. those two aformentioned addComponent calls were indeed adding the component, but deferred removals were removing the component from both entities the next time the query was called! 😆

thanks much for creating the issue and persisting through my short-sightedness! 😵

**Comment by NateTheGreatt** [comment]
bug fixed without `defineSystem` 🙌
shoutout to @vegeta897 for the solution 🙏
great catch @luetkemj!
`0.3.21` published with the fix 👍
