### ISSUE TITLE
TypeScript port

### ISSUE THREAD

**Issue by dannyfritz** [NateTheGreatt/bitECS#57]
Is this a real intention?
https://github.com/NateTheGreatt/bitECS/blob/04f1faa/src/index.ts#L2
> // Typescript port is coming soon.

**Comment by NateTheGreatt** [comment]
yes _but_ i have a lot of internal changes i'm working on right now that may shift the internal architecture a bit, so i'm holding off for the moment.

changes include any/all/none query modifiers, and automatic resizing of data stores with workers so that the main thread isn't locked up when data stores need to grow

**Comment by Fi1osof** [comment]
@NateTheGreatt it's realy needed. Hard to use in TS project now.

**Comment by jorgenbuilder** [comment]
This repo looks awesome! I can't decide whether I'm silly for not trying it out because it isn't TS. 😅

**Comment by SupremeTechnopriest** [comment]
@jorgenbuilder It has typedefs and a typescript rewrite is definitely on the roadmap 🙂

**Comment by NateTheGreatt** [comment]
closing this as the rewrite is now on the `next` branch and being prepared for `main` :)

**Comment by artokun** [comment]
Very excited for this
