### ISSUE TITLE
How to rollback game state if derialize the world won't delete new created entities?

### ISSUE THREAD

**Issue by neroishero** [NateTheGreatt/bitECS#70]
I use bitEcs in my step-lock game as game states, somehow i let the client to predict next game frame state, if the predict state does not match the server's state, then I want to rollback the state to previous state.  I tried to serialize the world every frame and save the packet, then derialize the world with certain frame if the predict is wrong. But the derialization won't delete the entitis created by the prediction. How can I achieve this idea? Any suggestion would be helpful. Or is there any way I can directly repace the world's state with the packet?
Many thanks!

**Comment by NateTheGreatt** [comment]
good question! i hadn't considered a situation like this. luckily i'm in the process of rewriting serialization, and i believe i have a solution for component adds and removals. sit tight and i'll try my best to cater to your scenario :)

**Comment by briancw** [comment]
I am in a similar position. I am currently serializing the world on a server and deserializing it on a client and need to know when an entity has been removed by the server. I would like to be able to potentially miss an update from the server and still keep the client and server synced, so specifically sending a list of ents to remove is not preferable. Rather, I'd like to be able to just have the client determine when an entity has been removed because it is no longer being serialized.
My current approach to this in lieu of a method baked into bitECS is to set a UUID on each entity and then diff already known entities against ents from deserialization.
Here's a simplified version of how I'm going about this.

```
const knownEntities = new Map()
const renderSystem = (world) => {
  const now = Date.now()
  const ents = deserialize(world, serializedDataFromServer)
  for (let i = 0; i < ents.length; i += 1) {
    const entId = ents[i]
    const uuid = UUID.value[entId]
    if (!knownEntities.has(uuid)) {
      MyRenderLib.add(uuid)
      knownEntities.set(uuid, now)
    }
  }

  for (const [key, lastUpdate] of knownEntities) {
    if (lastUpdate !== now) {
      MyRenderLib.remove(key)
      knownEntities.delete(key)
    }
  }
}
```
It would make my setup much much simpler if bitECS's deserialization automatically removed entities from the world or returned a list of existing entities which are not present on the world.

**Comment by NateTheGreatt** [comment]
@briancw i can cater to removals being serialized, but i don't think i can cater to your specific scenario. it is not normal for networked games to serialize and send the state of every single entity in the game every single frame as that is highly inefficient. for example in the networking system i have devised i only send values for an entity component when the value changes.

**Comment by NateTheGreatt** [comment]
after pondering this for a bit longer, i think i see a generic solution for both of these situations: `snapshots`. these would entirely replace world state. however, i am not sure what the performance will be like for this concept just yet. stay tuned 🤞
