### ISSUE TITLE
Entity Exists

### ISSUE THREAD

**Issue by yairhaimo** [NateTheGreatt/bitECS#75]
Is there a way to see if an entity exists in the world?

**Comment by yairhaimo** [comment]
Ah, great. Didnt see it in the api docs.
Thanks!

**Comment by NateTheGreatt** [comment]
@vegeta897 @yairhaimo this API function hasn't been released yet FYI, but i will be publishing a release with it soon.

however, there is a caveat here, as explained in this issue:
https://github.com/NateTheGreatt/bitECS/issues/68#issuecomment-1028292178

tl;dr because entity IDs are recycled it is entirely possible that a new entity was created with the same ID that was removed. still working on a fix for this potentiality
